### ISSUE TITLE
`browsermob-core/src/test/groovy/net/lightbody/bmp/proxy/BindAddressTest.groovy` failed

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/browsermob-proxy#2]
```
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
3677    2023-11-06 19:41:44,356 INFO [MockServer thread for port: 0] org.mockserver.mockserver.MockServer - MockServer started on port: 54288
4431    2023-11-06 19:41:45,110 INFO [nioEventLoopGroup-3-1] org.mockserver.mockserver.MockServerHandler - creating expectation:

	{
	  "httpRequest" : {
	    "method" : "GET",
	    "path" : "/clientbind"
	  },
	  "times" : {
	    "remainingTimes" : 0,
	    "unlimited" : true
	  },
	  "timeToLive" : {
	    "unlimited" : true
	  },
	  "httpResponse" : {
	    "statusCode" : 200
	  }
	}


5476    2023-11-06 19:41:46,155 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Starting proxy at address: KAZUAKInoMacBook-Air-2.local/127.0.0.1:0
5481    2023-11-06 19:41:46,160 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy listening with TCP transport
5483    2023-11-06 19:41:46,162 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy started at address: /127.0.0.1:54290
5896    2023-11-06 19:41:46,575 INFO [nioEventLoopGroup-3-2] org.mockserver.matchers.HttpRequestMatcher - request:

	{
	  "method" : "GET",
	  "path" : "/clientbind",
	  "headers" : [ {
	    "name" : "Host",
	    "values" : [ "127.0.0.1:54288" ]
	  }, {
	    "name" : "User-Agent",
	    "values" : [ "Apache-HttpClient/4.5.3 (Java/1.8.0_392)" ]
	  }, {
	    "name" : "Via",
	    "values" : [ "1.1 browsermobproxy" ]
	  }, {
	    "name" : "Content-Length",
	    "values" : [ "0" ]
	  } ],
	  "keepAlive" : true,
	  "secure" : false
	}

 matched expectation:

	{
	  "method" : "GET",
	  "path" : "/clientbind"
	}


5901    2023-11-06 19:41:46,580 INFO [nioEventLoopGroup-3-2] org.mockserver.mockserver.MockServerHandler - returning response:

	{
	  "statusCode" : 200
	}

 for request:

	{
	  "method" : "GET",
	  "path" : "/clientbind",
	  "headers" : [ {
	    "name" : "Host",
	    "values" : [ "127.0.0.1:54288" ]
	  }, {
	    "name" : "User-Agent",
	    "values" : [ "Apache-HttpClient/4.5.3 (Java/1.8.0_392)" ]
	  }, {
	    "name" : "Via",
	    "values" : [ "1.1 browsermobproxy" ]
	  }, {
	    "name" : "Content-Length",
	    "values" : [ "0" ]
	  } ],
	  "keepAlive" : true,
	  "secure" : false
	}


5928    2023-11-06 19:41:46,607 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Shutting down proxy server immediately (non-graceful)
5928    2023-11-06 19:41:46,607 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Closing all channels (non-graceful)
5935    2023-11-06 19:41:46,614 INFO [main] org.littleshoot.proxy.impl.ServerGroup - Shutting down server group event loops (non-graceful)
5942    2023-11-06 19:41:46,621 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Done shutting down proxy server

java.lang.AssertionError: Expected exception: org.apache.http.conn.HttpHostConnectException

	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)

5985    2023-11-06 19:41:46,664 INFO [MockServer thread for port: 0] org.mockserver.mockserver.MockServer - MockServer started on port: 54294
6006    2023-11-06 19:41:46,685 INFO [nioEventLoopGroup-8-1] org.mockserver.mockserver.MockServerHandler - creating expectation:

	{
	  "httpRequest" : {
	    "method" : "GET",
	    "path" : "/clientbind"
	  },
	  "times" : {
	    "remainingTimes" : 0,
	    "unlimited" : true
	  },
	  "timeToLive" : {
	    "unlimited" : true
	  },
	  "httpResponse" : {
	    "statusCode" : 200
	  }
	}


6017    2023-11-06 19:41:46,696 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Starting proxy at address: localhost/127.0.0.1:0
6021    2023-11-06 19:41:46,700 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy listening with TCP transport
6024    2023-11-06 19:41:46,703 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy started at address: /127.0.0.1:54296
6079    2023-11-06 19:41:46,758 INFO [nioEventLoopGroup-8-2] org.mockserver.matchers.HttpRequestMatcher - request:

	{
	  "method" : "GET",
	  "path" : "/clientbind",
	  "headers" : [ {
	    "name" : "Host",
	    "values" : [ "127.0.0.1:54294" ]
	  }, {
	    "name" : "User-Agent",
	    "values" : [ "Apache-HttpClient/4.5.3 (Java/1.8.0_392)" ]
	  }, {
	    "name" : "Via",
	    "values" : [ "1.1 browsermobproxy" ]
	  }, {
	    "name" : "Content-Length",
	    "values" : [ "0" ]
	  } ],
	  "keepAlive" : true,
	  "secure" : false
	}

 matched expectation:

	{
	  "method" : "GET",
	  "path" : "/clientbind"
	}


6084    2023-11-06 19:41:46,763 INFO [nioEventLoopGroup-8-2] org.mockserver.mockserver.MockServerHandler - returning response:

	{
	  "statusCode" : 200
	}

 for request:

	{
	  "method" : "GET",
	  "path" : "/clientbind",
	  "headers" : [ {
	    "name" : "Host",
	    "values" : [ "127.0.0.1:54294" ]
	  }, {
	    "name" : "User-Agent",
	    "values" : [ "Apache-HttpClient/4.5.3 (Java/1.8.0_392)" ]
	  }, {
	    "name" : "Via",
	    "values" : [ "1.1 browsermobproxy" ]
	  }, {
	    "name" : "Content-Length",
	    "values" : [ "0" ]
	  } ],
	  "keepAlive" : true,
	  "secure" : false
	}


6106    2023-11-06 19:41:46,785 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Shutting down proxy server immediately (non-graceful)
6107    2023-11-06 19:41:46,786 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Closing all channels (non-graceful)
6107    2023-11-06 19:41:46,786 INFO [main] org.littleshoot.proxy.impl.ServerGroup - Shutting down server group event loops (non-graceful)
6118    2023-11-06 19:41:46,797 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Done shutting down proxy server
6142    2023-11-06 19:41:46,821 INFO [MockServer thread for port: 0] org.mockserver.mockserver.MockServer - MockServer started on port: 54300
6145    2023-11-06 19:41:46,824 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Starting proxy at address: 0.0.0.0/0.0.0.0:0
6148    2023-11-06 19:41:46,827 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy listening with TCP transport
6149    2023-11-06 19:41:46,828 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy started at address: /0:0:0:0:0:0:0:0:54301
6201    2023-11-06 19:41:46,880 INFO [LittleProxy-2-ProxyToServerWorker-0] org.littleshoot.proxy.impl.ProxyToServerConnection - (CONNECTING) [id: 0xc6a66647, L:0.0.0.0/0.0.0.0:54303]: Connection to upstream server failed
io.netty.channel.AbstractChannel$AnnotatedSocketException: Can't assign requested address: www.google.com/172.217.26.228:80
	at sun.nio.ch.Net.connect0(Native Method) ~[?:1.8.0_392]
	at sun.nio.ch.Net.connect(Net.java:482) ~[?:1.8.0_392]
	at sun.nio.ch.Net.connect(Net.java:474) ~[?:1.8.0_392]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647) ~[?:1.8.0_392]
	at io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:83) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:80) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_392]
	at io.netty.util.internal.SocketUtils.connect(SocketUtils.java:80) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:244) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:205) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1234) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:539) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:524) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.connect(ChannelOutboundHandlerAdapter.java:47) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:539) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:524) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.connect(ChannelOutboundHandlerAdapter.java:47) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:539) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:524) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.connect(ChannelOutboundHandlerAdapter.java:47) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:539) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:524) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:50) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:539) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:524) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:984) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:223) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.bootstrap.Bootstrap$2.run(Bootstrap.java:168) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:399) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131) [netty-all-4.0.51.Final.jar:4.0.51.Final]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392]
Caused by: java.net.BindException: Can't assign requested address
	... 32 more
6214    2023-11-06 19:41:46,893 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Shutting down proxy server immediately (non-graceful)
6214    2023-11-06 19:41:46,893 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Closing all channels (non-graceful)
6215    2023-11-06 19:41:46,894 INFO [main] org.littleshoot.proxy.impl.ServerGroup - Shutting down server group event loops (non-graceful)
6225    2023-11-06 19:41:46,904 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Done shutting down proxy server
6256    2023-11-06 19:41:46,935 INFO [MockServer thread for port: 0] org.mockserver.mockserver.MockServer - MockServer started on port: 54305
6271    2023-11-06 19:41:46,950 INFO [nioEventLoopGroup-15-1] org.mockserver.mockserver.MockServerHandler - creating expectation:

	{
	  "httpRequest" : {
	    "method" : "GET",
	    "path" : "/serverbind"
	  },
	  "times" : {
	    "remainingTimes" : 0,
	    "unlimited" : true
	  },
	  "timeToLive" : {
	    "unlimited" : true
	  },
	  "httpResponse" : {
	    "statusCode" : 200
	  }
	}


6278    2023-11-06 19:41:46,957 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Starting proxy at address: 0.0.0.0/0.0.0.0:0
6280    2023-11-06 19:41:46,959 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy listening with TCP transport
6284    2023-11-06 19:41:46,963 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy started at address: /0:0:0:0:0:0:0:0:54307
6300    2023-11-06 19:41:46,979 INFO [nioEventLoopGroup-15-2] org.mockserver.matchers.HttpRequestMatcher - request:

	{
	  "method" : "GET",
	  "path" : "/serverbind",
	  "headers" : [ {
	    "name" : "Host",
	    "values" : [ "127.0.0.1:54305" ]
	  }, {
	    "name" : "User-Agent",
	    "values" : [ "Apache-HttpClient/4.5.3 (Java/1.8.0_392)" ]
	  }, {
	    "name" : "Via",
	    "values" : [ "1.1 browsermobproxy" ]
	  }, {
	    "name" : "Content-Length",
	    "values" : [ "0" ]
	  } ],
	  "keepAlive" : true,
	  "secure" : false
	}

 matched expectation:

	{
	  "method" : "GET",
	  "path" : "/serverbind"
	}


6303    2023-11-06 19:41:46,982 INFO [nioEventLoopGroup-15-2] org.mockserver.mockserver.MockServerHandler - returning response:

	{
	  "statusCode" : 200
	}

 for request:

	{
	  "method" : "GET",
	  "path" : "/serverbind",
	  "headers" : [ {
	    "name" : "Host",
	    "values" : [ "127.0.0.1:54305" ]
	  }, {
	    "name" : "User-Agent",
	    "values" : [ "Apache-HttpClient/4.5.3 (Java/1.8.0_392)" ]
	  }, {
	    "name" : "Via",
	    "values" : [ "1.1 browsermobproxy" ]
	  }, {
	    "name" : "Content-Length",
	    "values" : [ "0" ]
	  } ],
	  "keepAlive" : true,
	  "secure" : false
	}


6310    2023-11-06 19:41:46,989 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Shutting down proxy server immediately (non-graceful)
6311    2023-11-06 19:41:46,990 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Closing all channels (non-graceful)
6312    2023-11-06 19:41:46,991 INFO [main] org.littleshoot.proxy.impl.ServerGroup - Shutting down server group event loops (non-graceful)
6317    2023-11-06 19:41:46,996 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Done shutting down proxy server

Process finished with exit code 255
```

**Comment by kazurayam** [comment]
I retried this. It passed now.

Possibly when I got the error as above, I was downloading giga-bytes of files on another machine beside. So the network was not stable enough.
