### ISSUE TITLE
`browsermob-core/src/test/groovy/net/lightbody/bmp/util/BrowserMobHttpUtilTest.groovy` failed

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/browsermob-proxy#4]
```
/Users/kazuakiurayama/.sdkman/candidates/java/current/bin/java -ea -Xmx1g -XX:MaxPermSize=256m -Didea.test.cyclic.buffer.size=1048576 -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=54759:/Applications/IntelliJ IDEA.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA.app/Contents/plugins/junit/lib/junit5-rt.jar:/Applications/IntelliJ IDEA.app/Contents/plugins/junit/lib/junit-rt.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/jre/lib/charsets.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/jre/lib/ext/cldrdata.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/jre/lib/ext/dnsns.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/jre/lib/ext/jaccess.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/jre/lib/ext/jfxrt.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/jre/lib/ext/localedata.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/jre/lib/ext/nashorn.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/jre/lib/ext/sunec.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/jre/lib/ext/sunjce_provider.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/jre/lib/ext/sunpkcs11.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/jre/lib/ext/zipfs.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/jre/lib/jce.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/jre/lib/jfr.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/jre/lib/jfxswt.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/jre/lib/jsse.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/jre/lib/management-agent.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/jre/lib/resources.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/jre/lib/rt.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/lib/ant-javafx.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/lib/dt.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/lib/javafx-mx.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/lib/jconsole.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/lib/packager.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/lib/sa-jdi.jar:/Users/kazuakiurayama/.sdkman/candidates/java/current/lib/tools.jar:/Users/kazuakiurayama/github/browsermob-proxy/browsermob-core/target/test-classes:/Users/kazuakiurayama/github/browsermob-proxy/browsermob-core/target/classes:/Users/kazuakiurayama/.m2/repository/net/lightbody/bmp/littleproxy/1.1.0-beta-bmp-17/littleproxy-1.1.0-beta-bmp-17.jar:/Users/kazuakiurayama/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/Users/kazuakiurayama/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.8.9/jackson-core-2.8.9.jar:/Users/kazuakiurayama/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.8.9/jackson-databind-2.8.9.jar:/Users/kazuakiurayama/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.8.9/jackson-annotations-2.8.9.jar:/Users/kazuakiurayama/.m2/repository/com/google/guava/guava/23.0-android/guava-23.0-android.jar:/Users/kazuakiurayama/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar:/Users/kazuakiurayama/.m2/repository/com/google/errorprone/error_prone_annotations/2.0.18/error_prone_annotations-2.0.18.jar:/Users/kazuakiurayama/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar:/Users/kazuakiurayama/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar:/Users/kazuakiurayama/.m2/repository/dnsjava/dnsjava/2.1.8/dnsjava-2.1.8.jar:/Users/kazuakiurayama/.m2/repository/org/seleniumhq/selenium/selenium-api/2.53.1/selenium-api-2.53.1.jar:/Users/kazuakiurayama/.m2/repository/com/google/code/gson/gson/2.3.1/gson-2.3.1.jar:/Users/kazuakiurayama/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/Users/kazuakiurayama/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar:/Users/kazuakiurayama/.m2/repository/com/jcraft/jzlib/1.1.3/jzlib-1.1.3.jar:/Users/kazuakiurayama/.m2/repository/io/netty/netty-all/4.0.51.Final/netty-all-4.0.51.Final.jar:/Users/kazuakiurayama/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.58/bcprov-jdk15on-1.58.jar:/Users/kazuakiurayama/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.58/bcpkix-jdk15on-1.58.jar:/Users/kazuakiurayama/github/browsermob-proxy/mitm/target/classes:/Users/kazuakiurayama/.m2/repository/org/javassist/javassist/3.21.0-GA/javassist-3.21.0-GA.jar:/Users/kazuakiurayama/.m2/repository/org/apache/logging/log4j/log4j-api/2.9.0/log4j-api-2.9.0.jar:/Users/kazuakiurayama/.m2/repository/org/apache/logging/log4j/log4j-core/2.9.0/log4j-core-2.9.0.jar:/Users/kazuakiurayama/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.9.0/log4j-slf4j-impl-2.9.0.jar:/Users/kazuakiurayama/.m2/repository/org/seleniumhq/selenium/selenium-firefox-driver/2.53.1/selenium-firefox-driver-2.53.1.jar:/Users/kazuakiurayama/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/2.53.1/selenium-remote-driver-2.53.1.jar:/Users/kazuakiurayama/.m2/repository/cglib/cglib-nodep/2.1_3/cglib-nodep-2.1_3.jar:/Users/kazuakiurayama/.m2/repository/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.jar:/Users/kazuakiurayama/.m2/repository/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.jar:/Users/kazuakiurayama/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/Users/kazuakiurayama/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar:/Users/kazuakiurayama/.m2/repository/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar:/Users/kazuakiurayama/.m2/repository/net/java/dev/jna/jna-platform/4.1.0/jna-platform-4.1.0.jar:/Users/kazuakiurayama/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/kazuakiurayama/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar:/Users/kazuakiurayama/.m2/repository/junit/junit/4.12/junit-4.12.jar:/Users/kazuakiurayama/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/Users/kazuakiurayama/.m2/repository/org/mockito/mockito-core/2.8.47/mockito-core-2.8.47.jar:/Users/kazuakiurayama/.m2/repository/net/bytebuddy/byte-buddy/1.6.14/byte-buddy-1.6.14.jar:/Users/kazuakiurayama/.m2/repository/net/bytebuddy/byte-buddy-agent/1.6.14/byte-buddy-agent-1.6.14.jar:/Users/kazuakiurayama/.m2/repository/org/objenesis/objenesis/2.5/objenesis-2.5.jar:/Users/kazuakiurayama/.m2/repository/org/mock-server/mockserver-netty/3.10.4/mockserver-netty-3.10.4.jar:/Users/kazuakiurayama/.m2/repository/org/mock-server/mockserver-client-java/3.10.4/mockserver-client-java-3.10.4.jar:/Users/kazuakiurayama/.m2/repository/org/mock-server/mockserver-core/3.10.4/mockserver-core-3.10.4.jar:/Users/kazuakiurayama/.m2/repository/javax/servlet/javax.servlet-api/3.0.1/javax.servlet-api-3.0.1.jar:/Users/kazuakiurayama/.m2/repository/com/twitter/finagle-native_2.11/6.33.0/finagle-native_2.11-6.33.0.jar:/Users/kazuakiurayama/.m2/repository/org/scala-lang/scala-library/2.11.7/scala-library-2.11.7.jar:/Users/kazuakiurayama/.m2/repository/com/twitter/finagle-core_2.11/6.33.0/finagle-core_2.11-6.33.0.jar:/Users/kazuakiurayama/.m2/repository/com/twitter/util-app_2.11/6.32.0/util-app_2.11-6.32.0.jar:/Users/kazuakiurayama/.m2/repository/com/twitter/util-cache_2.11/6.32.0/util-cache_2.11-6.32.0.jar:/Users/kazuakiurayama/.m2/repository/com/twitter/util-codec_2.11/6.32.0/util-codec_2.11-6.32.0.jar:/Users/kazuakiurayama/.m2/repository/com/twitter/util-collection_2.11/6.32.0/util-collection_2.11-6.32.0.jar:/Users/kazuakiurayama/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/kazuakiurayama/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar:/Users/kazuakiurayama/.m2/repository/com/twitter/util-core_2.11/6.32.0/util-core_2.11-6.32.0.jar:/Users/kazuakiurayama/.m2/repository/com/twitter/util-function_2.11/6.32.0/util-function_2.11-6.32.0.jar:/Users/kazuakiurayama/.m2/repository/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.jar:/Users/kazuakiurayama/.m2/repository/com/twitter/util-hashing_2.11/6.32.0/util-hashing_2.11-6.32.0.jar:/Users/kazuakiurayama/.m2/repository/com/twitter/util-jvm_2.11/6.32.0/util-jvm_2.11-6.32.0.jar:/Users/kazuakiurayama/.m2/repository/com/twitter/util-lint_2.11/6.32.0/util-lint_2.11-6.32.0.jar:/Users/kazuakiurayama/.m2/repository/com/twitter/util-logging_2.11/6.32.0/util-logging_2.11-6.32.0.jar:/Users/kazuakiurayama/.m2/repository/com/twitter/util-registry_2.11/6.32.0/util-registry_2.11-6.32.0.jar:/Users/kazuakiurayama/.m2/repository/com/twitter/util-stats_2.11/6.32.0/util-stats_2.11-6.32.0.jar:/Users/kazuakiurayama/.m2/repository/com/twitter/jsr166e/1.0.0/jsr166e-1.0.0.jar:/Users/kazuakiurayama/.m2/repository/io/netty/netty/3.10.1.Final/netty-3.10.1.Final.jar:/Users/kazuakiurayama/.m2/repository/com/twitter/finagle-http_2.11/6.33.0/finagle-http_2.11-6.33.0.jar:/Users/kazuakiurayama/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/Users/kazuakiurayama/.m2/repository/org/bouncycastle/bcmail-jdk15on/1.52/bcmail-jdk15on-1.52.jar:/Users/kazuakiurayama/.m2/repository/org/skyscreamer/jsonassert/1.2.3/jsonassert-1.2.3.jar:/Users/kazuakiurayama/.m2/repository/org/json/json/20090211/json-20090211.jar:/Users/kazuakiurayama/.m2/repository/com/github/fge/json-schema-validator/2.2.6/json-schema-validator-2.2.6.jar:/Users/kazuakiurayama/.m2/repository/joda-time/joda-time/2.3/joda-time-2.3.jar:/Users/kazuakiurayama/.m2/repository/com/googlecode/libphonenumber/libphonenumber/6.2/libphonenumber-6.2.jar:/Users/kazuakiurayama/.m2/repository/com/github/fge/json-schema-core/1.2.5/json-schema-core-1.2.5.jar:/Users/kazuakiurayama/.m2/repository/com/github/fge/uri-template/0.9/uri-template-0.9.jar:/Users/kazuakiurayama/.m2/repository/com/github/fge/msg-simple/1.1/msg-simple-1.1.jar:/Users/kazuakiurayama/.m2/repository/com/github/fge/btf/1.2/btf-1.2.jar:/Users/kazuakiurayama/.m2/repository/com/github/fge/jackson-coreutils/1.8/jackson-coreutils-1.8.jar:/Users/kazuakiurayama/.m2/repository/org/mozilla/rhino/1.7R4/rhino-1.7R4.jar:/Users/kazuakiurayama/.m2/repository/javax/mail/mailapi/1.4.3/mailapi-1.4.3.jar:/Users/kazuakiurayama/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar:/Users/kazuakiurayama/.m2/repository/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar:/Users/kazuakiurayama/.m2/repository/xerces/xercesImpl/2.4.0/xercesImpl-2.4.0.jar:/Users/kazuakiurayama/.m2/repository/janino/janino/2.5.10/janino-2.5.10.jar:/Users/kazuakiurayama/.m2/repository/org/mock-server/mockserver-logging/3.10.4/mockserver-logging-3.10.4.jar:/Users/kazuakiurayama/.m2/repository/org/eclipse/jetty/jetty-server/7.6.16.v20140903/jetty-server-7.6.16.v20140903.jar:/Users/kazuakiurayama/.m2/repository/org/eclipse/jetty/orbit/javax.servlet/2.5.0.v201103041518/javax.servlet-2.5.0.v201103041518.jar:/Users/kazuakiurayama/.m2/repository/org/eclipse/jetty/jetty-continuation/7.6.16.v20140903/jetty-continuation-7.6.16.v20140903.jar:/Users/kazuakiurayama/.m2/repository/org/eclipse/jetty/jetty-http/7.6.16.v20140903/jetty-http-7.6.16.v20140903.jar:/Users/kazuakiurayama/.m2/repository/org/eclipse/jetty/jetty-io/7.6.16.v20140903/jetty-io-7.6.16.v20140903.jar:/Users/kazuakiurayama/.m2/repository/org/eclipse/jetty/jetty-servlet/7.6.16.v20140903/jetty-servlet-7.6.16.v20140903.jar:/Users/kazuakiurayama/.m2/repository/org/eclipse/jetty/jetty-security/7.6.16.v20140903/jetty-security-7.6.16.v20140903.jar:/Users/kazuakiurayama/.m2/repository/org/eclipse/jetty/jetty-servlets/7.6.16.v20140903/jetty-servlets-7.6.16.v20140903.jar:/Users/kazuakiurayama/.m2/repository/org/eclipse/jetty/jetty-client/7.6.16.v20140903/jetty-client-7.6.16.v20140903.jar:/Users/kazuakiurayama/.m2/repository/org/eclipse/jetty/jetty-util/7.6.16.v20140903/jetty-util-7.6.16.v20140903.jar:/Users/kazuakiurayama/.m2/repository/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar:/Users/kazuakiurayama/.m2/repository/org/codehaus/groovy/groovy-all/2.4.12/groovy-all-2.4.12.jar com.intellij.rt.junit.JUnitStarter -ideVersion5 -junit4 net.lightbody.bmp.proxy.NewHarTest
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
3633    2023-11-06 19:47:06,345 INFO [MockServer thread for port: 0] org.mockserver.mockserver.MockServer - MockServer started on port: 54768
4321    2023-11-06 19:47:07,033 INFO [nioEventLoopGroup-3-1] org.mockserver.mockserver.MockServerHandler - creating expectation:

	{
	  "httpRequest" : {
	    "method" : "GET",
	    "path" : "/testCaptureResponseCookiesInHar"
	  },
	  "times" : {
	    "remainingTimes" : 1,
	    "unlimited" : false
	  },
	  "timeToLive" : {
	    "unlimited" : true
	  },
	  "httpResponse" : {
	    "statusCode" : 200,
	    "headers" : [ {
	      "name" : "Set-Cookie",
	      "values" : [ "max-age-cookie=mock-value; Max-Age=3153600000", "expires-cookie=mock-value; Expires=Wed, 15 Mar 2022 12:00:00 GMT" ]
	    } ],
	    "body" : "success"
	  }
	}


5303    2023-11-06 19:47:08,015 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Starting proxy at address: 0.0.0.0/0.0.0.0:0
5308    2023-11-06 19:47:08,020 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy listening with TCP transport
5311    2023-11-06 19:47:08,023 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy started at address: /0:0:0:0:0:0:0:0:54772
5690    2023-11-06 19:47:08,402 WARN [LittleProxy-0-ClientToProxyWorker-0] net.lightbody.bmp.mitm.util.SslUtil - Disabling upstream server certificate verification. This will allow attackers to intercept communications with upstream servers.
6646    2023-11-06 19:47:09,358 INFO [nioEventLoopGroup-3-2] org.mockserver.matchers.HttpRequestMatcher - request:

	{
	  "method" : "GET",
	  "path" : "/testCaptureResponseCookiesInHar",
	  "headers" : [ {
	    "name" : "Host",
	    "values" : [ "localhost:54768" ]
	  }, {
	    "name" : "User-Agent",
	    "values" : [ "Apache-HttpClient/4.5.3 (Java/1.8.0_392)" ]
	  }, {
	    "name" : "Via",
	    "values" : [ "1.1 browsermobproxy" ]
	  }, {
	    "name" : "Content-Length",
	    "values" : [ "0" ]
	  } ],
	  "keepAlive" : true,
	  "secure" : true
	}

 matched expectation:

	{
	  "method" : "GET",
	  "path" : "/testCaptureResponseCookiesInHar"
	}


6650    2023-11-06 19:47:09,362 INFO [nioEventLoopGroup-3-2] org.mockserver.mockserver.MockServerHandler - returning response:

	{
	  "statusCode" : 200,
	  "headers" : [ {
	    "name" : "Set-Cookie",
	    "values" : [ "max-age-cookie=mock-value; Max-Age=3153600000", "expires-cookie=mock-value; Expires=Wed, 15 Mar 2022 12:00:00 GMT" ]
	  } ],
	  "body" : "success"
	}

 for request:

	{
	  "method" : "GET",
	  "path" : "/testCaptureResponseCookiesInHar",
	  "headers" : [ {
	    "name" : "Host",
	    "values" : [ "localhost:54768" ]
	  }, {
	    "name" : "User-Agent",
	    "values" : [ "Apache-HttpClient/4.5.3 (Java/1.8.0_392)" ]
	  }, {
	    "name" : "Via",
	    "values" : [ "1.1 browsermobproxy" ]
	  }, {
	    "name" : "Content-Length",
	    "values" : [ "0" ]
	  } ],
	  "keepAlive" : true,
	  "secure" : true
	}


6687    2023-11-06 19:47:09,399 WARN [main] org.apache.http.client.protocol.ResponseProcessCookies - Invalid cookie header: "Set-Cookie: expires-cookie=mock-value; Expires=Wed, 15 Mar 2022 12:00:00 GMT". Invalid 'expires' attribute: Wed, 15 Mar 2022 12:00:00 GMT
7306    2023-11-06 19:47:10,018 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Shutting down proxy server immediately (non-graceful)
7306    2023-11-06 19:47:10,018 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Closing all channels (non-graceful)
7312    2023-11-06 19:47:10,024 INFO [main] org.littleshoot.proxy.impl.ServerGroup - Shutting down server group event loops (non-graceful)
7323    2023-11-06 19:47:10,035 INFO [main] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Done shutting down proxy server

java.lang.AssertionError: Incorrect expiration date in cookie with Expires
Expected: <Tue Mar 15 21:00:00 JST 2022>
     but: was null
Expected :<Tue Mar 15 21:00:00 JST 2022>
Actual   :null
<Click to see difference>


	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert$assertThat$0.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:222)
	at net.lightbody.bmp.proxy.NewHarTest.testCaptureResponseCookiesInHar(NewHarTest.groovy:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)


```

**Comment by kazurayam** [comment]
`browsermob-core/src/test/groovy/net/lightbody/bmp/util/BrowserMobHttpUtilTest.groovy` is not failing. Look at the error message carefully. The error is a duplicate to the #3
